### ISSUE TITLE
https support ?

### ISSUE THREAD

**Issue by mtnasution** [hidden-refuge/spi#1]
is this SPI can support https caching ?.. sorry for my english

**Comment by hidden-refuge** [comment]
Hello mtnasution,

Squid is a pure HTTP proxy however you can of course browse HTTPs sites with it. This installer isn't caching anything! This is part of the anonymous configuration. Cache would be conflicting with being anonymous (because it can be used to identify who has visited what together with other logs) so the configuration included with this installer does not cache content of visited sites and it does not log what was visited.

I hope I could answer your question. If not please reply.
